### ISSUE TITLE
random freezes in wemos

### ISSUE THREAD

**Issue by vakaobr** [aetios50/PincabLedStrip#5]
Hello there,

I'm experiencing random crashes of wemos (the wemos status led stop blinking and dof/doflinx effects in led strips got frozen also) while using this code.

My first suspicious was my cabinet windows install, did a fresh one but still getting the same. Don't now if its related to have the 8 strips connected (that not should be a problem), somebody already saw/got something similar ?

**Comment by yoyofr** [comment]
Hi, I will try to do some tests with your updates / 8 led trips. Maybe related to memory constraints on the wemos ? Does it work better if you limit to 6 or 7 led strips in the firmware ?

**Comment by vakaobr** [comment]
Hello!

I can imagine something related to memory constraints also (but the odd its using the old "slow" code it works ok).

I did a single test using 7 strips, the behaviour was the same, will try later on with 6 and see what happens.

**Comment by yoyofr** [comment]
maybe try to reduce the MaxLedsPerStrip in ledstrip.h

**Comment by vakaobr** [comment]
reduced the MaxledsPerStrip in ledstrip.h, don't have any errors in directouput.log but also don't work.

Logfile:

[DirectOutput.log](https://github.com/aetios50/PincabLedStrip/files/5703657/DirectOutput.log)

**Comment by vakaobr** [comment]
Mystery solved: The wemos was NOT set to 160mhz (was in default 80Mhz), I'll add that information in README and create a PR to it
